Fixed the illegal string offset warning
mt-support/tribe-ext-list-venues-organizers-shortcodes pull request #4
Opened 2018-11-16 11:58 UTC by andrasguseo

Added a check to make sure the right type is passed when creating shortcode.
Originally $atts would come empty, which is a string. In this case it needs to be converted to array.

Based on:
https://codex.wordpress.org/Shortcode_API#Overview
"$atts - an associative array of attributes, or an empty string if no attributes are given"

Central ticket:
https://central.tri.be/issues/115913

2018-11-18 14:30 UTC, cliffordp requested changes
Please change `if ( is_string( $atts ) )` to `if ( ! is_array( $atts ) )` since we know we'll be acting on the array. Good job.

2018-11-19 12:26 UTC, cliffordp requested changes

2018-11-19 12:26 UTC, cliffordp commented on readme.txt
> += [2.1.2] 2018-11-16 =
Correct the date

2018-11-19 12:26 UTC, cliffordp commented on tribe-ext-list-venues-organizers-shortcodes.php
> +		 * @param $atts - an associative array of attributes, or an empty string if no attributes are given
Add summary line to docblock

2018-11-19 12:26 UTC, cliffordp commented on tribe-ext-list-venues-organizers-shortcodes.php
> +		 * @param $atts - an associative array of attributes, or an empty string if no attributes are given
Add summary line to docblock

2018-11-19 20:19 UTC, andrasguseo commented on tribe-ext-list-venues-organizers-shortcodes.php
> +		 * @param $atts - an associative array of attributes, or an empty string if no attributes are given
Done

2018-11-19 20:19 UTC, andrasguseo commented on readme.txt
> += [2.1.2] 2018-11-16 =
Done

2018-11-19 20:20 UTC, andrasguseo commented on tribe-ext-list-venues-organizers-shortcodes.php
> +		 * @param $atts - an associative array of attributes, or an empty string if no attributes are given
Done

2018-11-19 22:30 UTC, cliffordp approved these changes

2018-11-20 08:43 UTC, merged